In [1]:

# tuple - store data in a collection
# immutable
t1 = (1,2,3)
t1

(1, 2, 3)

In [2]:
t1[1]

2

In [3]:
t1[1] = 5

TypeError: 'tuple' object does not support item assignment

In [4]:
l1 = [1,2,3]
l1[1] = 6
l1

[1, 6, 3]

In [5]:
# set (mängd)
{1,2,1,1,1,1}

{1, 2}

In [6]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [7]:
(i for i in range(5))

<generator object <genexpr> at 0x104e36080>

In [8]:
tuple(i for i in range(5))

(0, 1, 2, 3, 4)

In [10]:
text = "(23,24)"

data = eval(text)
data

(23, 24)

In [13]:
data[0]

23

In [14]:
list_2d = [[20,23], [22,10], [15,15]]

In [15]:
list_2d

[[20, 23], [22, 10], [15, 15]]

In [16]:
list_2d[0]

[20, 23]

In [17]:
raw = "(23,24)\n(20,20)\n(10,15)"
print(raw)

(23,24)
(20,20)
(10,15)


In [22]:
# list comprehension
data = [eval(coordinate) for coordinate in raw.split("\n")]
data

[(23, 24), (20, 20), (10, 15)]

In [25]:
data = []
for coordinate in raw.split("\n"):
    data.append(eval(coordinate))

data

[(23, 24), (20, 20), (10, 15)]

In [26]:
raw = "(12,32)"
data = eval(raw)
data

(12, 32)

In [28]:
data[0]

12

In [3]:
with open("../data/python/pikachu.txt", "r") as file:
    raw = file.read()

print(raw)

(width (cm), height (cm))
(18.137772263313835, 44.951493566608946)
(26.648661832322336, 41.49878057639454)
(26.180524428318897, 39.38100083914504)
(24.44364396490554, 40.175758410355904)
(21.201902279430513, 36.21004195868266)
(25.691541582957697, 37.24697337031557)
(19.338626083150515, 38.38085562147455)
(23.21718300802926, 40.88308718457233)
(23.444684475950478, 37.30114732596577)
(29.445791130252964, 37.20217384451559)
(28.51023528453833, 35.709930860090324)
(21.16066860901309, 41.31102957270099)
(24.00703335660358, 37.28941783811155)
(20.143822566361578, 44.054200130061275)
(28.951534072137846, 43.59635400253747)
(28.4462228380412, 35.70857349888654)
(21.581337497383593, 37.380046343689955)
(25.66739393839206, 41.68977778296281)
(25.30764253725807, 37.14236807370439)
(19.834071222595618, 36.32311848725025)
(27.150129600901813, 44.35514240580671)
(24.472548361435507, 40.710430933252844)
(27.3435177435667, 39.726710263117944)
(24.36424406634213, 42.846194242907536)
(18.00686275353532

In [9]:
data_text = raw.split("\n")[1:-1]
eval(data_text[0])

(18.137772263313835, 44.951493566608946)

In [12]:
eval(data_text[0])[0] + 50

68.13777226331383

In [21]:
test = raw.split("\n")[1:-1][0]

test_string = test[1:-1]
test_string

'18.137772263313835, 44.951493566608946'

In [26]:
test_string.split(", ")

['18.137772263313835', '44.951493566608946']

In [28]:
data_point1 = float(test_string.split(", ")[0]), float(test_string.split(", ")[1])
data_point1

(18.137772263313835, 44.951493566608946)

In [14]:
import numpy as np 
merged_data = []
data_list = np.array([(2,3), (12,32)])
for point in data_list:
    merged_data.append(point)

merged_data


[array([2, 3]), array([12, 32])]

In [22]:
x = np.concatenate([np.array(merged_data), np.ones((2,1))], axis = 1)

x

array([[ 2.,  3.,  1.],
       [12., 32.,  1.]])

In [24]:
(x[:,0]-3)**2

array([ 1., 81.])

In [2]:
import numpy as np 

data = np.random.randint(1,7, (20,2))
data

array([[3, 6],
       [2, 4],
       [3, 6],
       [6, 1],
       [6, 1],
       [5, 2],
       [2, 6],
       [5, 2],
       [2, 2],
       [5, 1],
       [3, 1],
       [6, 3],
       [1, 2],
       [4, 2],
       [3, 6],
       [5, 5],
       [4, 6],
       [2, 3],
       [6, 4],
       [1, 2]])

In [6]:
test = (20,30)
# vectorisation in numpy
np.sqrt((data[:,0] - test[0])**2 + (data[:,1]-test[1])**2)


array([29.41088234, 31.6227766 , 29.41088234, 32.20248438, 32.20248438,
       31.76476035, 30.        , 31.76476035, 33.28663395, 32.64965543,
       33.61547263, 30.41381265, 33.83784863, 32.24903099, 29.41088234,
       29.15475947, 28.8444102 , 32.44996148, 29.52964612, 33.83784863])

In [8]:
test_data = "(23, 32), (13,23), (22,19), (10,15)"
test_data

'(23, 32), (13,23), (22,19), (10,15)'

In [15]:
cleaned_test = eval(f"[{test_data}]")
cleaned_test

[(23, 32), (13, 23), (22, 19), (10, 15)]

In [26]:
fake_data = np.concatenate([np.random.randint(1,7,(20,2)), np.ones((20,1))], axis=1)
fake_data[:10,2] = 0
fake_data

array([[5., 4., 0.],
       [3., 5., 0.],
       [3., 1., 0.],
       [3., 5., 0.],
       [4., 2., 0.],
       [2., 1., 0.],
       [2., 4., 0.],
       [5., 5., 0.],
       [2., 4., 0.],
       [1., 4., 0.],
       [1., 6., 1.],
       [5., 1., 1.],
       [2., 6., 1.],
       [1., 5., 1.],
       [4., 4., 1.],
       [1., 6., 1.],
       [1., 2., 1.],
       [6., 5., 1.],
       [5., 6., 1.],
       [1., 2., 1.]])

In [38]:
fake_data[10:,1] = fake_data[10:,1]+20


In [40]:
fake_data[10:,0] = fake_data[10:,0]+20
fake_data

array([[ 5.,  4.,  0.],
       [ 3.,  5.,  0.],
       [ 3.,  1.,  0.],
       [ 3.,  5.,  0.],
       [ 4.,  2.,  0.],
       [ 2.,  1.,  0.],
       [ 2.,  4.,  0.],
       [ 5.,  5.,  0.],
       [ 2.,  4.,  0.],
       [ 1.,  4.,  0.],
       [21., 26.,  1.],
       [25., 21.,  1.],
       [22., 26.,  1.],
       [21., 25.,  1.],
       [24., 24.,  1.],
       [21., 26.,  1.],
       [21., 22.,  1.],
       [26., 25.,  1.],
       [25., 26.,  1.],
       [21., 22.,  1.]])

In [50]:
test = (15,10)
distances = np.sqrt((fake_data[:,0] - test[0])**2 + (fake_data[:,1] - test[1])**2)
distances

array([11.66190379, 13.        , 15.        , 13.        , 13.60147051,
       15.8113883 , 14.31782106, 11.18033989, 14.31782106, 15.23154621,
       17.08800749, 14.86606875, 17.4642492 , 16.15549442, 16.64331698,
       17.08800749, 13.41640786, 18.60107524, 18.86796226, 13.41640786])

In [51]:
sorted_indices = np.argsort(distances)
distances[sorted_indices]

array([11.18033989, 11.66190379, 13.        , 13.        , 13.41640786,
       13.41640786, 13.60147051, 14.31782106, 14.31782106, 14.86606875,
       15.        , 15.23154621, 15.8113883 , 16.15549442, 16.64331698,
       17.08800749, 17.08800749, 17.4642492 , 18.60107524, 18.86796226])

In [52]:
fake_data[:,2][sorted_indices]

array([0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1.,
       1., 1., 1.])

In [55]:
fake_data[:,2][sorted_indices][:5].sum() # > 3 -> pikachu else pichu

1.0

---

In [56]:
fake_data

array([[ 5.,  4.,  0.],
       [ 3.,  5.,  0.],
       [ 3.,  1.,  0.],
       [ 3.,  5.,  0.],
       [ 4.,  2.,  0.],
       [ 2.,  1.,  0.],
       [ 2.,  4.,  0.],
       [ 5.,  5.,  0.],
       [ 2.,  4.,  0.],
       [ 1.,  4.,  0.],
       [21., 26.,  1.],
       [25., 21.,  1.],
       [22., 26.,  1.],
       [21., 25.,  1.],
       [24., 24.,  1.],
       [21., 26.,  1.],
       [21., 22.,  1.],
       [26., 25.,  1.],
       [25., 26.,  1.],
       [21., 22.,  1.]])

In [63]:
np.argmin(np.sqrt((fake_data[:,1] - 20)**2 + (fake_data[:,0] - 25)**2))

11

Training
- 45 pikachu
- 45 pichu

Test 
- 5 pikachu
- 5 pichu

- Test point - classify the test points 
- check the accuracy

---

In [2]:
string = "(43.2, 23)"
string

'(43.2, 23)'

In [4]:
data = eval(string)
data 

(43.2, 23)

In [5]:
data[0]

43.2

In [6]:
data[1]

23

In [7]:
string[0]

'('

In [3]:
import matplotlib.font_manager

fonts = set(f.name for f in matplotlib.font_manager.fontManager.ttflist)
for font in sorted(fonts):
    print(font)


.Aqua Kana
.Keyboard
.New York
.SF Arabic
.SF Compact
.SF Compact Rounded
.SF NS Mono
.SF NS Rounded
Academy Engraved LET
Al Bayan
Al Nile
Al Tarikh
American Typewriter
Andale Mono
Apple Braille
Apple Chancery
Apple SD Gothic Neo
Apple Symbols
AppleGothic
AppleMyungjo
Arial
Arial Black
Arial Hebrew
Arial Narrow
Arial Rounded MT Bold
Arial Unicode MS
Athelas
Avenir
Avenir Next
Avenir Next Condensed
Ayuthaya
Baghdad
Bangla MN
Bangla Sangam MN
Baskerville
Beirut
Big Caslon
Bodoni 72
Bodoni 72 Oldstyle
Bodoni 72 Smallcaps
Bodoni Ornaments
Bradley Hand
Brush Script MT
Chalkboard
Chalkboard SE
Chalkduster
Charter
Cochin
Comic Sans MS
Copperplate
Corsiva Hebrew
Courier
Courier New
DIN Alternate
DIN Condensed
Damascus
DecoType Naskh
DejaVu Sans
DejaVu Sans Display
DejaVu Sans Mono
DejaVu Serif
DejaVu Serif Display
Devanagari MT
Devanagari Sangam MN
Didot
Diwan Kufi
Diwan Thuluth
Euphemia UCAS
Farah
Farisi
Futura
Galvji
Geeza Pro
Geneva
Georgia
Gill Sans
Gujarati MT
Gujarati Sangam MN
Gurmukhi 

In [4]:
import pandas as pd

df = pd.read_excel("../data/data_processing/calories.xlsx")
df.head()

FoodCategory             FoodItem per100grams Cals_per100grams  \
0  CannedFruit           Applesauce        100g           62 cal   
1  CannedFruit      Canned Apricots        100g           48 cal   
2  CannedFruit  Canned Blackberries        100g           92 cal   
3  CannedFruit   Canned Blueberries        100g           88 cal   
4  CannedFruit      Canned Cherries        100g           54 cal   

  KJ_per100grams  
0         260 kJ  
1         202 kJ  
2         386 kJ  
3         370 kJ  
4         227 kJ

In [17]:
df["Cals_per100grams"] = df["Cals_per100grams"].str[:-4].astype(int) 
df["KJ_per100grams"] = df["KJ_per100grams"].str[:-2].astype(int) 


In [22]:
(df["KJ_per100grams"] - df["Cals_per100grams"])/df["KJ_per100grams"]

0       0.761538
1       0.762376
2       0.761658
3       0.762162
4       0.762115
          ...   
2220    0.761868
2221    0.762002
2222    0.761873
2223    0.761905
2224    0.761865
Length: 2225, dtype: float64