# Python fundamentals part 2

- error handling 
  - try-except
  - different types of errors
- file handling
- functions
- matplotlib 
- numpy

## Error handling
- syntax error
- runtime errors (exceptions) 
- logical errors

### syntax error

In [1]:
prin("linear regression is a supervised learning algorithm")

NameError: name 'prin' is not defined

In [2]:
print("linear regression is a supervised learning algorithm")

linear regression is a supervised learning algorithm


### runtime error

In [5]:
# [0,1,2,3,4]
numbers = list(range(5))

numbers[5]

IndexError: list index out of range

### logical error
- can be hard to detect

In [8]:
import numpy as np 

radius = 5

# circle area is actually pi*r^2
circle_area = np.pi*radius
print(f"{circle_area = :.2f} area units")

circle_area = 15.71 area units


### try-except

In [10]:
age = float(input("Enter your age: "))

print(age)

-32.0


In [12]:
age = float(input("Enter your age: "))
if not 0 <= age <= 125:
    raise ValueError(f"You entered {age}, age must be between 0 and 125")

ValueError: You entered -412.0, age must be between 0 and 125

In [13]:
age = float(input("Enter your age: "))
if not 0 <= age <= 125:
    raise ValueError(f"You entered {age}, age must be between 0 and 125")

ValueError: You entered 145.0, age must be between 0 and 125

In [17]:
while True:
    try:
        age = float(input("Enter your age: "))
        if not 0 <= age <= 125:
            raise ValueError(f"You entered {age}, age must be between 0 and 125")
        print(f"You are {age} years old")
        break
    except ValueError as err:
        print(err)



You entered -321.0, age must be between 0 and 125
You entered 127.0, age must be between 0 and 125
You are 0.0 years old


## Functions

- reuse code
- organize code
- increase readability
- modular code
- DRY

In [19]:
# number is input parameter
def cuber(number):
    return number**3

# call the function cuber with input argument 2
cuber(2)


8

In [20]:
cubes = [cuber(number) for number in range(5)]
cubes

[0, 1, 8, 27, 64]

### Default value

In [21]:
for i in range(1, 5):
    print(i*"x ")

x 
x x 
x x x 
x x x x 


In [25]:
# void function - returns None, but has a side effect by printing
def draw_ascii_triangle(number_rows=5):
    for i in range(1, number_rows+1):
        print(i*"x ")

draw_ascii_triangle()



x 
x x 
x x x 
x x x x 
x x x x x 


In [26]:
# 10 overwrites the default value of 5
draw_ascii_triangle(10)

x 
x x 
x x x 
x x x x 
x x x x x 
x x x x x x 
x x x x x x x 
x x x x x x x x 
x x x x x x x x x 
x x x x x x x x x x 


### Arbitrary arguments, *args

- arbitrary number of positional arguments

In [28]:
def average(*numbers):
    sum_ = 0
    for number in numbers:
        sum_ += number

    return sum_/len(numbers)

# (1+2+3)/3
average(1,2,3)

2.0

In [29]:
average(1,2,34,5,12,51,23,34)

20.25

### Keyword arguments, **kwargs

In [35]:
def simulate_dices(throws=1, dices=2):
    return np.random.randint(1,7, size=(throws, dices))

simulate_dices()

array([[1, 1]])

In [37]:
simulate_dices(5,2)

array([[6, 6],
       [2, 6],
       [3, 3],
       [2, 1],
       [1, 3]])

In [39]:
simulate_dices(throws=6, dices=4).shape

(6, 4)

In [40]:
simulate_dices(dices=3)

array([[4, 4, 3]])

### Lambda functions
- anonymous functions
- can be used inside other functions
- examples will be shown later in the course

In [41]:
cuber = lambda x: x**3

cuber(5)

125

## Matplotlib