# Code alongs missing data

## Simulating missing values

In [10]:
import numpy as np 
import pandas as pd 

# in order to get comparable results 
np.random.seed(42)
n = 8 

random_matrix = np.random.randint(1,10, size=(n,n))
random_matrix



array([[7, 4, 8, 5, 7, 3, 7, 8],
       [5, 4, 8, 8, 3, 6, 5, 2],
       [8, 6, 2, 5, 1, 6, 9, 1],
       [3, 7, 4, 9, 3, 5, 3, 7],
       [5, 9, 7, 2, 4, 9, 2, 9],
       [5, 2, 4, 7, 8, 3, 1, 4],
       [2, 8, 4, 2, 6, 6, 4, 6],
       [2, 2, 4, 8, 7, 9, 8, 5]])

In [12]:
random_matrix.size

64

In [11]:
index = np.random.choice(random_matrix.size, 10, replace=False)
index

array([21, 20, 36,  3,  5, 29, 12, 37, 41, 33])

In [13]:
# flattens our 8x8 2D-array into a 64 1D-array 
random_matrix.ravel()

array([7, 4, 8, 5, 7, 3, 7, 8, 5, 4, 8, 8, 3, 6, 5, 2, 8, 6, 2, 5, 1, 6,
       9, 1, 3, 7, 4, 9, 3, 5, 3, 7, 5, 9, 7, 2, 4, 9, 2, 9, 5, 2, 4, 7,
       8, 3, 1, 4, 2, 8, 4, 2, 6, 6, 4, 6, 2, 2, 4, 8, 7, 9, 8, 5])

In [17]:
# need to convert our random_matrix into floats 
# because can't assign None to int as np.nan is float
random_matrix = random_matrix*1.0
random_matrix.ravel()[index] = None
random_matrix

array([[ 7.,  4.,  8., nan,  7., nan,  7.,  8.],
       [ 5.,  4.,  8.,  8., nan,  6.,  5.,  2.],
       [ 8.,  6.,  2.,  5., nan, nan,  9.,  1.],
       [ 3.,  7.,  4.,  9.,  3., nan,  3.,  7.],
       [ 5., nan,  7.,  2., nan, nan,  2.,  9.],
       [ 5., nan,  4.,  7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.,  6.,  4.,  6.],
       [ 2.,  2.,  4.,  8.,  7.,  9.,  8.,  5.]])