# Code alongs missing data

## Simulating missing values

In [10]:
import numpy as np 
import pandas as pd 

# in order to get comparable results 
np.random.seed(42)
n = 8 

random_matrix = np.random.randint(1,10, size=(n,n))
random_matrix



array([[7, 4, 8, 5, 7, 3, 7, 8],
       [5, 4, 8, 8, 3, 6, 5, 2],
       [8, 6, 2, 5, 1, 6, 9, 1],
       [3, 7, 4, 9, 3, 5, 3, 7],
       [5, 9, 7, 2, 4, 9, 2, 9],
       [5, 2, 4, 7, 8, 3, 1, 4],
       [2, 8, 4, 2, 6, 6, 4, 6],
       [2, 2, 4, 8, 7, 9, 8, 5]])

In [12]:
random_matrix.size

64

In [11]:
# sampling without replacement
index = np.random.choice(random_matrix.size, 10, replace=False)
index

array([21, 20, 36,  3,  5, 29, 12, 37, 41, 33])

In [13]:
# flattens our 8x8 2D-array into a 64 1D-array 
random_matrix.ravel()

array([7, 4, 8, 5, 7, 3, 7, 8, 5, 4, 8, 8, 3, 6, 5, 2, 8, 6, 2, 5, 1, 6,
       9, 1, 3, 7, 4, 9, 3, 5, 3, 7, 5, 9, 7, 2, 4, 9, 2, 9, 5, 2, 4, 7,
       8, 3, 1, 4, 2, 8, 4, 2, 6, 6, 4, 6, 2, 2, 4, 8, 7, 9, 8, 5])

In [17]:
# need to convert our random_matrix into floats 
# because can't assign None to int as np.nan is float
random_matrix = random_matrix*1.0
random_matrix.ravel()[index] = None
random_matrix

array([[ 7.,  4.,  8., nan,  7., nan,  7.,  8.],
       [ 5.,  4.,  8.,  8., nan,  6.,  5.,  2.],
       [ 8.,  6.,  2.,  5., nan, nan,  9.,  1.],
       [ 3.,  7.,  4.,  9.,  3., nan,  3.,  7.],
       [ 5., nan,  7.,  2., nan, nan,  2.,  9.],
       [ 5., nan,  4.,  7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.,  6.,  4.,  6.],
       [ 2.,  2.,  4.,  8.,  7.,  9.,  8.,  5.]])

In [23]:
scores = pd.DataFrame(
    random_matrix,
    columns=[f"Round {i}" for i in range(1, 9)],
    index=[f"Player {i}" for i in range(1, 9)],
)

scores

Round 1  Round 2  Round 3  Round 4  Round 5  Round 6  Round 7  \
Player 1      7.0      4.0      8.0      NaN      7.0      NaN      7.0   
Player 2      5.0      4.0      8.0      8.0      NaN      6.0      5.0   
Player 3      8.0      6.0      2.0      5.0      NaN      NaN      9.0   
Player 4      3.0      7.0      4.0      9.0      3.0      NaN      3.0   
Player 5      5.0      NaN      7.0      2.0      NaN      NaN      2.0   
Player 6      5.0      NaN      4.0      7.0      8.0      3.0      1.0   
Player 7      2.0      8.0      4.0      2.0      6.0      6.0      4.0   
Player 8      2.0      2.0      4.0      8.0      7.0      9.0      8.0   

          Round 8  
Player 1      8.0  
Player 2      2.0  
Player 3      1.0  
Player 4      7.0  
Player 5      9.0  
Player 6      4.0  
Player 7      6.0  
Player 8      5.0

## Handle missing values

In [24]:
scores.isnull()

Round 1  Round 2  Round 3  Round 4  Round 5  Round 6  Round 7  \
Player 1    False    False    False     True    False     True    False   
Player 2    False    False    False    False     True    False    False   
Player 3    False    False    False    False     True     True    False   
Player 4    False    False    False    False    False     True    False   
Player 5    False     True    False    False     True     True    False   
Player 6    False     True    False    False    False    False    False   
Player 7    False    False    False    False    False    False    False   
Player 8    False    False    False    False    False    False    False   

          Round 8  
Player 1    False  
Player 2    False  
Player 3    False  
Player 4    False  
Player 5    False  
Player 6    False  
Player 7    False  
Player 8    False

In [25]:
scores.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, Player 1 to Player 8
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Round 1  8 non-null      float64
 1   Round 2  6 non-null      float64
 2   Round 3  8 non-null      float64
 3   Round 4  7 non-null      float64
 4   Round 5  5 non-null      float64
 5   Round 6  4 non-null      float64
 6   Round 7  8 non-null      float64
 7   Round 8  8 non-null      float64
dtypes: float64(8)
memory usage: 576.0+ bytes


In [27]:
scores

Round 1  Round 2  Round 3  Round 4  Round 5  Round 6  Round 7  \
Player 1      7.0      4.0      8.0      NaN      7.0      NaN      7.0   
Player 2      5.0      4.0      8.0      8.0      NaN      6.0      5.0   
Player 3      8.0      6.0      2.0      5.0      NaN      NaN      9.0   
Player 4      3.0      7.0      4.0      9.0      3.0      NaN      3.0   
Player 5      5.0      NaN      7.0      2.0      NaN      NaN      2.0   
Player 6      5.0      NaN      4.0      7.0      8.0      3.0      1.0   
Player 7      2.0      8.0      4.0      2.0      6.0      6.0      4.0   
Player 8      2.0      2.0      4.0      8.0      7.0      9.0      8.0   

          Round 8  
Player 1      8.0  
Player 2      2.0  
Player 3      1.0  
Player 4      7.0  
Player 5      9.0  
Player 6      4.0  
Player 7      6.0  
Player 8      5.0

In [26]:
scores.dropna()

Round 1  Round 2  Round 3  Round 4  Round 5  Round 6  Round 7  \
Player 7      2.0      8.0      4.0      2.0      6.0      6.0      4.0   
Player 8      2.0      2.0      4.0      8.0      7.0      9.0      8.0   

          Round 8  
Player 7      6.0  
Player 8      5.0